### ISSUE TITLE
Separation of async and algorithm

### ISSUE THREAD

**Issue by mattmassicotte** [Finnvoor/FindFaster#1]
Hello! Thank you so much for making this package, it's awesome.

I was considering how I might incorporate it into my own code, and I immediately ran into a problem. There are places were I could benefit from a fast search, but *require* it to be synchronous. Looking at your implementation, I think the concurrency features and core algorithm are actually completely distinct.

What do you think about separating these two concepts? This way, users could opt for the synchronous approach when needed, along with a nice async wrapper for if/when that is more appropriate.

**Comment by finnvoor** [comment]
Sounds like a good idea, a closure-based version may also be useful to some. 

Everything inside the Task {}'s is the actual implementation, so it should be easy to separate. The only thing async related is the Task.isCancelled check, but I suppose that's fine to leave in non-async versions.

**Comment by mattmassicotte** [comment]
I'm glad - I think it will make the library way more general.

**Comment by finnvoor** [comment]
WDYT about #3, does that cover all your use cases?

**Comment by mattmassicotte** [comment]
I think it looks fantastic! 🎉
